services:
  - type: web
    name: mypdf
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y libreoffice ghostscript poppler-utils
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT