services:
  - type: web
    name: mypdf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app
UPLOAD_DIR = "/data/uploads"
OUTPUT_DIR = "/data/outputs"
